// Generated by CoffeeScript 1.6.2
var ArrayCollection, Events, global, _, _ref;

global = typeof exports !== "undefined" && exports !== null ? exports : window;

if (typeof exports !== 'undefined') {
  _ = require('underscore')._;
  _ref = require('js-arraycollection'), ArrayCollection = _ref.ArrayCollection, Events = _ref.Events;
}

(function() {
  'use strict';
  var FooDB;

  if (!global.FooDB) {
    return FooDB = global.FooDB = (function() {
      FooDB.prototype.__collection = new ArrayCollection([]);

      function FooDB(data) {
        var _this = this;

        _.extend(this, Events);
        if (data != null) {
          this.create(data);
        }
        this.__collection.on('collectionChanged', function(data) {
          console.log('trigering collectionChanged');
          return _this.trigger('collectionChanged', data);
        });
      }

      FooDB.prototype.create = function(obj) {
        var res,
          _this = this;

        if (!obj) {
          return null;
        }
        this.__collection.addAll(res = _.map((_.isArray(obj) ? obj : [obj]), function(v, k) {
          return _.extend(v, {
            objectId: _.uniqueId()
          });
        }));
        return res;
      };

      FooDB.prototype.read = function(where) {
        if ((where != null)) {
          return _.where(this.__collection.__list, where);
        } else {
          return this.__collection.__list;
        }
      };

      FooDB.prototype.update = function(where, obj) {
        var _this = this;

        if (!where) {
          return null;
        }
        return _.map(this.read(where), function(v, k) {
          return _.extend(v, obj);
        });
      };

      FooDB.prototype.destroy = function(id) {
        var idx, ref;

        if (((ref = this.read({
          objectId: id
        })) != null) && ((idx = this.__collection.getItemIndex(ref)) != null)) {
          return this.__collection.removeItemAt(idx);
        }
      };

      return FooDB;

    })();
  }
}).call(this);
